security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern: ^/login$
            anonymous: true
        main_register:
            pattern: ^/register/$
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider:   fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: false
#                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
            logout:
                path: /logout
                target: /login
            anonymous: true
#            access_denied_handler: app.AccesRefuseListener

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
